trigger:
- master

pool:
  name: flm-pool

steps:

# 🔹 Build using Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'

# 🔹 Deploy WAR to Tomcat
- task: TomcatDeployment@1
  inputs:
    TomcatUrl: 'http://20.39.194.213:8080'
    Username: 'tomcat'
    Password: 'admin@123'
    Warfile: 'target/myweb-8.7.3.war'
    Context: '/ourapp'
    ServerVersion: '7OrAbove'