trigger:
- master

pool:
  name: flm-pool

steps:

# 🔹 Build using Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'

# 🔹 Deploy WAR to Tomcat
- task: TomcatDeployment@1
  inputs:
    TomcatUrl: '$(URL)'
    Username: 'admin'
    Password: '$(password)'
    Warfile: 'target/*.war'
    Context: '/ourapp'
    ServerVersion: '7OrAbove'